name: Go  # The name of the workflow that will appear on Github

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        go: [1.24]
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: Test
      run: |
        go test -v -cover $(go list -buildvcs=false ./... | grep -v examples) -coverprofile coverage 
        go tool cover -func coverage -o coverage  # Replaces coverage with the analysis of coverage

    - name: Update coverage report
      uses: ncruces/go-coverage-report@v0
      with:
        report: true
        chart: true
        amend: true
        coverage-file: coverage
      if: |
        matrix.os == 'ubuntu-latest' &&
        github.event_name == 'push'
      continue-on-error: true
